In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

device_type = 'cuda'
huggingface_token = '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'

tokenizer = AutoTokenizer.from_pretrained(
    "google/gemma-7b",
    token=huggingface_token
)
big_model = AutoModelForCausalLM.from_pretrained(
    "google/gemma-7b",
    token=huggingface_token,
    torch_dtype=torch.bfloat16
).to(device_type)
small_model = AutoModelForCausalLM.from_pretrained(
    "google/gemma-2b",
    token=huggingface_token,
    torch_dtype=torch.bfloat16
).to(device_type)

Gemma's activation function should be approximate GeLU and not exact GeLU.
Changing the activation function to `gelu_pytorch_tanh`.if you want to use the legacy `gelu`, edit the `model.config` to set `hidden_activation=gelu`   instead of `hidden_act`. See https://github.com/huggingface/transformers/pull/29402 for more details.


Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
input_text = 'once upon'
gamma = 5

In [ ]:
# generate gamma tokens using the small model
input_ids = tokenizer(
    input_text,
    return_tensors='pt'
)['input_ids'].to(device_type)[0]
small_model_output = small_model.generate(
    input_ids[None],
    max_new_tokens=gamma,
    return_dict_in_generate=True,
    output_scores=True
)

In [ ]:
# calculate q (the probability the small model assigned to the generated tokens)
small_model_generated_tokens = small_model_output.sequences[0, -gamma:]
q = torch.stack(small_model_output.scores, dim=1)[0].softmax(dim=-1)
q_of_generated = q[torch.arange(gamma), small_model_generated_tokens]
q_of_generated

tensor([0.9676, 0.9292, 0.2872, 0.2792, 0.7979], device='cuda:0')

In [ ]:
# calculate p (the probability the big model assigned to the generated tokens)
p = big_model(small_model_output.sequences).logits.softmax(dim=-1)[0, -gamma-1:]
p_of_generated = p[torch.arange(gamma), small_model_generated_tokens]
p_of_generated

tensor([0.9662, 0.9092, 0.2634, 0.3173, 0.7331], device='cuda:0',
       grad_fn=<IndexBackward0>)

In [ ]:
# acceptance rule
ratio = p_of_generated / q_of_generated
is_accepted = torch.rand(gamma).to(device_type) < ratio
index_to_reject = torch.argmin(torch.cat([
    is_accepted,
    torch.tensor([False]).to(device_type)
]).to(int))

In [ ]:
accepted_tokens = small_model_generated_tokens[:index_to_reject]

if index_to_reject == gamma:  # all tokens are accepted
  p_for_sample = p[-1]
else:  # some token was rejected
  p_for_sample = p[index_to_reject] - q[index_to_reject]
  p_for_sample[p_for_sample<0] = 0
  p_for_sample /= p_for_sample.sum()

In [ ]:
# generate one token using the big model
big_model_generated_token = torch.multinomial(p_for_sample, num_samples=1)
generated_tokens = torch.cat([accepted_tokens, big_model_generated_token])
generated_tokens

tensor([   476,   1069, 235269,   1104,    729,    476], device='cuda:0')

In [ ]:
import colorama

In [ ]:
# glue all the above code together and wrap it inside a while loop that
# generates the number of tokens requested by the user
input_text = 'once upon'
gamma = 5
seqlen = 30
input_ids = tokenizer(
    input_text,
    return_tensors='pt'
)['input_ids'].to(device_type)[0]
all_ids = input_ids

while len(all_ids) - len(input_ids) < seqlen:
  # generate gamma tokens using the small model
  small_model_output = small_model.generate(
      all_ids[None],
      max_new_tokens=gamma,
      return_dict_in_generate=True,
      output_scores=True
  )

  # calculate q (the probability the small model assigned to the generated tokens)
  small_model_generated_tokens = small_model_output.sequences[0, -gamma:]
  q = torch.stack(small_model_output.scores, dim=1)[0].softmax(dim=-1)
  q_of_generated = q[torch.arange(gamma), small_model_generated_tokens]

  # calculate p (the probability the big model assigned to the generated tokens)
  p = big_model(small_model_output.sequences).logits.softmax(dim=-1)[0, -gamma-1:]
  p_of_generated = p[torch.arange(gamma), small_model_generated_tokens]

  # acceptance rule
  ratio = p_of_generated / q_of_generated
  is_accepted = torch.rand(gamma).to(device_type) < ratio
  index_to_reject = torch.argmin(torch.cat([
      is_accepted,
      torch.tensor([False]).to(device_type)
  ]).to(int))
  accepted_tokens = small_model_generated_tokens[:index_to_reject]

  if index_to_reject == gamma:  # all tokens are accepted
    p_for_sample = p[-1]
  else:  # some token was rejected
    p_for_sample = p[index_to_reject] - q[index_to_reject]
    p_for_sample[p_for_sample<0] = 0
    p_for_sample /= p_for_sample.sum()

  # generate one token using the big model
  big_model_generated_token = torch.multinomial(p_for_sample, num_samples=1)

  print(colorama.Fore.BLACK, tokenizer.decode(all_ids), end='')
  print(colorama.Fore.BLUE, tokenizer.decode(accepted_tokens), end='')
  if index_to_reject < gamma:
    print(colorama.Fore.RED, tokenizer.decode(small_model_generated_tokens[index_to_reject]), end='')
  print(colorama.Fore.GREEN, tokenizer.decode(big_model_generated_token), end='')
  print()

  all_ids = torch.cat([all_ids, accepted_tokens, big_model_generated_token])

 <bos>once upon  a time, there was  a
 <bos>once upon a time, there was a   little  place
 <bos>once upon a time, there was a place  called  the  yak
 <bos>once upon a time, there was a place called yak  sha ima
 <bos>once upon a time, there was a place called yakima . it was a place  where
 <bos>once upon a time, there was a place called yakima. it was a place where   people  heaven
 <bos>once upon a time, there was a place called yakima. it was a place where heaven  and earth  met  meet
 <bos>once upon a time, there was a place called yakima. it was a place where heaven and earth meet . it was a place  of
 <bos>once upon a time, there was a place called yakima. it was a place where heaven and earth meet. it was a place of   peace  gentle
 <bos>once upon a time, there was a place called yakima. it was a place where heaven and earth meet. it was a place of gentle  people,  where  and
